version: '3'
services:
  hyperf-skeleton:
    container_name: hyperf-skeleton
    image: hyperf-skeleton
    build:
      context: .
    volumes:
      - ./:/opt/www
      - /mnt/d/Code/packagist:/opt/packagist
    ports:
      - "9501:9501"
    environment:
      - APP_ENV=dev
      - SCAN_CACHEABLE=false
    networks:
      - hyperf-net
  mysql:
    image: mysql:8.0
    env_file:
      - ./.env
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "3310:3306"
    volumes:
      - hyperf-skeleton_db_data:/var/lib/mysql
    networks:
      - hyperf-net
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - hyperf-skeleton_redis_data:/data
    networks:
      - hyperf-net

volumes:
  hyperf-skeleton_db_data:
  hyperf-skeleton_redis_data:

networks:
  hyperf-net:
    driver: bridge

